const appConfig={reportUrl:null,staticFestivalBase:'./festival/',mapViewportSearch:false};
const monetizationConfig={sponsoredFestivals:false,localAds:false,affiliate:false,radarPlus:false,displayAds:false,partnerContactUrl:null,maxPromotedFestivals:1,homeFeedInterval:8};
const features={radarPlus:false};
const monetizationItems=[];
const monetizationItemSchema={id:null,type:null,title:null,description:null,image:null,url:null,region:null,city:null,festivalId:null,startDate:null,endDate:null,priority:0,sponsored:true,active:false};
const festivalSchemaFields=['id','slug','title','description','region','city','address','latitude','longitude','startDate','endDate','category','tags','price','free','night','parking','image','source','sourceUrl','updatedAt','promoted','promotionPriority','promotionStartDate','promotionEndDate'];
let festivals=[],datasetUpdatedAt=null,favorites=FestivalStorage.read('festival-favorites',[]),compareCandidates=FestivalDecision.compareIds(),month=new Date(),period='all',purpose='all',quickFree=false,quickNight=false,map,markerLayer,userPosition=null,nearMode=false,userMarker=null,filteredFestivals=[],detailMap=null,currentFestivalId=null,previousFocus=null;
const DAY=86400000,tagLabels={date:'데이트',family:'아이와',friends:'친구와',solo:'혼자',food:'먹거리',night:'야간',photo:'사진',traditional:'전통',nature:'자연',performance:'공연',experience:'체험'};
const radarPreferenceSchema={region:null,category:null,freeOnly:false,weekendOnly:false};
const radarPlusPreferenceSchema={regions:[],categories:[],conditions:[],alerts:{newFestival:false,d7:false,lastWeekend:false,freeFestival:false}};
const festivalReportSchema={festivalId:null,crowded:null,parkingHard:null,worthVisiting:null,visited:false,createdAt:null};
const SEO_DEFAULT={title:'전국축제달력 | 이번 주말 어디 갈까?',description:'대한민국 전국 축제를 날짜와 지역, 지도에서 탐색하고 저장하세요.',url:'https://junhassss.github.io/korea-festival-calendar/'};
const seoulParts=date=>Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date).filter(v=>v.type!=='literal').map(v=>[v.type,v.value]));
const startOfDay=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate());
const parseDate=iso=>{let [y,m,d]=iso.split('-').map(Number);return new Date(y,m-1,d)};
const isoDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const todayDate=()=>{let p=seoulParts(new Date());return new Date(Number(p.year),Number(p.month)-1,Number(p.day))};
const addDays=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x};
const fmt=d=>d.replaceAll('-','.');
function weekendRange(offset=0){let d=todayDate(),untilSaturday=(6-d.getDay()+7)%7,saturday=addDays(d,untilSaturday+offset*7);return {start:saturday,end:addDays(saturday,1)}}
function overlaps(f,start,end){return parseDate(f.startDate)<=end&&parseDate(f.endDate)>=start}
function getDaysUntilEnd(f,base=todayDate()){return Math.ceil((parseDate(f.endDate)-base)/DAY)}
function isThisWeekend(f){let w=weekendRange(0);return overlaps(f,w.start,w.end)}
function isNextWeekend(f){let w=weekendRange(1);return overlaps(f,w.start,w.end)}
function active(f,base=todayDate()){return parseDate(f.startDate)<=base&&parseDate(f.endDate)>=base}
function getFestivalStatus(f,base=todayDate()){let start=parseDate(f.startDate),end=parseDate(f.endDate),toStart=Math.ceil((start-base)/DAY),toEnd=Math.ceil((end-base)/DAY);if(toEnd<0)return '종료';if(toStart===0&&toEnd===0)return '오늘 시작 · 오늘 종료';if(toStart===0)return '오늘 시작';if(toEnd===0)return '오늘 종료';if(toStart>0)return '예정';if(toEnd===1)return 'D-1';if(toEnd===3)return 'D-3';let weekEnd=addDays(base,6-base.getDay());if(end<=weekEnd)return '이번 주 종료';if(isThisWeekend(f)&&!isNextWeekend(f))return '마지막 주말';return '진행중'}
function getFilterState(){return {query:query.value.trim().toLowerCase(),region:region.value,category:category.value,price:price.value,period,purpose,freeOnly:quickFree,nightOnly:quickNight,radius:Number(distance.value),nearMode,userPosition,sort:sort.value}}
function filterStateFromUrl(){let p=new URLSearchParams(location.search);return {query:p.get('q')||'',region:p.get('region')||'전체 지역',category:p.get('category')||'전체 카테고리',price:p.get('price')||'전체 요금',period:p.get('period')||'all',purpose:p.get('purpose')||'all',freeOnly:p.get('free')==='1',nightOnly:p.get('night')==='1',sort:p.get('sort')||'recommended'}}
function applyUrlFilterState(){let s=filterStateFromUrl();query.value=s.query;region.value=s.region;category.value=s.category;price.value=s.price;sort.value=s.sort;period=s.period;purpose=s.purpose;quickFree=s.freeOnly;quickNight=s.nightOnly;document.querySelectorAll('[data-period]').forEach(b=>b.classList.toggle('active',b.dataset.period===period));document.querySelectorAll('[data-purpose]').forEach(b=>b.classList.toggle('active',b.dataset.purpose===purpose));freeChip.classList.toggle('active',quickFree);nightChip.classList.toggle('active',quickNight)}
function syncFilterUrl(){let url=new URL(location.href),state=getFilterState(),set=(key,value,defaultValue)=>value!==defaultValue?url.searchParams.set(key,value):url.searchParams.delete(key);set('q',query.value.trim(),'');set('region',state.region,'전체 지역');set('category',state.category,'전체 카테고리');set('price',state.price,'전체 요금');set('period',state.period,'all');set('purpose',state.purpose,'all');state.freeOnly?url.searchParams.set('free','1'):url.searchParams.delete('free');state.nightOnly?url.searchParams.set('night','1'):url.searchParams.delete('night');set('sort',state.sort,'recommended');history.replaceState(history.state,'',url.pathname+url.search);}
function filterFestivals(list,state){let today=todayDate(),thisWeekend=weekendRange(0),nextWeekend=weekendRange(1);return list.filter(f=>(state.query||parseDate(f.endDate)>=today)&&(!state.query||(f.title+f.region+f.city+f.address).toLowerCase().includes(state.query))&&(state.region==='전체 지역'||f.region===state.region)&&(state.category==='전체 카테고리'||f.category===state.category)&&(state.price==='전체 요금'||(state.price==='무료')===f.free)&&(!state.freeOnly||f.free)&&(!state.nightOnly||f.night)&&(state.purpose==='all'||f.tags.includes(state.purpose))&&(state.period==='all'||state.period==='today'&&overlaps(f,today,today)||state.period==='weekend'&&overlaps(f,thisWeekend.start,thisWeekend.end)||state.period==='nextWeekend'&&overlaps(f,nextWeekend.start,nextWeekend.end)||state.period==='ongoing'&&active(f,today)||state.period==='endingSoon'&&active(f,today)&&getDaysUntilEnd(f,today)<=3)&&(!state.nearMode||state.userPosition&&distanceKm(state.userPosition.latitude,state.userPosition.longitude,f.latitude,f.longitude)<=state.radius))}
function sortFestivals(list,state){return [...list].sort((a,b)=>{if(state.sort==='soon')return parseDate(a.startDate)-parseDate(b.startDate);if(state.sort==='ending')return parseDate(a.endDate)-parseDate(b.endDate);if(state.sort==='free')return Number(b.free)-Number(a.free)||parseDate(a.startDate)-parseDate(b.startDate);if(state.sort==='distance'&&state.userPosition)return distanceKm(state.userPosition.latitude,state.userPosition.longitude,a.latitude,a.longitude)-distanceKm(state.userPosition.latitude,state.userPosition.longitude,b.latitude,b.longitude);return Number(active(b))-Number(active(a))||Math.abs(parseDate(a.startDate)-todayDate())-Math.abs(parseDate(b.startDate)-todayDate())})}
function heartVisual(){return `<svg class="heart-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 20.4 4.1 13A5.25 5.25 0 0 1 11.5 5.6l.5.55.5-.55A5.25 5.25 0 0 1 19.9 13Z"/></svg>`}
function heartButton(f){let liked=favorites.includes(f.id);return `<button class="heart ${liked?'liked':''}" data-fav-id="${f.id}" aria-label="${f.title} 축제 ${liked?'찜 해제':'찜하기'}" aria-pressed="${liked}" onclick="toggleFav('${f.id}',event)">${heartVisual(liked)}</button>`}
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function getMonetizationUrl(item){if(!item||!item.url)return null;try{let url=new URL(item.url,location.href);return ['http:','https:'].includes(url.protocol)?url.href:null}catch{return null}}
function trackMonetizationClick({itemId,type,festivalId=null,placement}){let event={event:'monetization_click',itemId,type,festivalId,placement,timestamp:new Date().toISOString()};window.dispatchEvent(new CustomEvent('monetization:click',{detail:event}));if(Array.isArray(window.dataLayer))window.dataLayer.push(event);return event}
function isMonetizationActive(item){let today=isoDate(todayDate());return !!item?.active&&(!item.startDate||item.startDate<=today)&&(!item.endDate||item.endDate>=today)}
function isPromotionActive(f){let today=isoDate(todayDate());return monetizationConfig.sponsoredFestivals&&f.promoted===true&&(!f.promotionStartDate||f.promotionStartDate<=today)&&(!f.promotionEndDate||f.promotionEndDate>=today)}
function renderSponsoredCard(item,placement='home_feed'){let url=getMonetizationUrl(item);if(!isMonetizationActive(item)||!url)return '';return `<article class="sponsoredcard"><div class="sponsoredbody"><span class="sponsoredlabel">Sponsored</span>${item.image?`<img src="${escapeHtml(item.image)}" alt="">`:''}<h3>${escapeHtml(item.title)}</h3>${item.description?`<p>${escapeHtml(item.description)}</p>`:''}<a class="sponsoredlink" href="${escapeHtml(url)}" target="_blank" rel="sponsored noopener noreferrer" onclick="trackMonetizationClick({itemId:'${escapeHtml(item.id)}',type:'${escapeHtml(item.type)}',festivalId:'${escapeHtml(item.festivalId||'')}',placement:'${placement}'})">자세히 보기 →</a></div></article>`}
function homeSponsoredItem(){return monetizationConfig.displayAds||monetizationConfig.localAds?monetizationItems.filter(isMonetizationActive).filter(v=>['banner','localAd','festivalPromotion'].includes(v.type)).sort((a,b)=>(b.priority||0)-(a.priority||0))[0]:null}
function renderFestivalFeed(list){let ad=homeSponsoredItem();if(!ad)return list.map((item,index)=>card(item,index)).join('');let parts=list.map((item,index)=>card(item,index));parts.splice(Math.min(monetizationConfig.homeFeedInterval,parts.length),0,renderSponsoredCard(ad,'home_feed'));return parts.join('')}
function renderFestivalExtras(f){let enabled=monetizationConfig.affiliate||monetizationConfig.localAds;if(!enabled)return '';let items=monetizationItems.filter(isMonetizationActive).filter(v=>v.festivalId===f.id||!v.festivalId&&v.region===f.region).sort((a,b)=>(b.priority||0)-(a.priority||0));if(!items.length)return '';let icons={hotel:'🏨',restaurant:'🍜',cafe:'☕',activity:'🎟',transport:'🚌',localAd:'📍'},cards=items.slice(0,4).map(item=>{let url=getMonetizationUrl(item);if(!url)return '';return `<a class="affiliatecard" href="${escapeHtml(url)}" target="_blank" rel="sponsored noopener noreferrer" onclick="trackMonetizationClick({itemId:'${escapeHtml(item.id)}',type:'${escapeHtml(item.type)}',festivalId:'${f.id}',placement:'festival_detail'})">${item.image?`<img src="${escapeHtml(item.image)}" alt="">`:''}<span><span class="sponsoredlabel">${item.sponsored?'Sponsored':'제휴'}</span><b>${icons[item.type]||'📍'} ${escapeHtml(item.title)}</b><br><small>${escapeHtml(item.description||'')}</small></span></a>`}).filter(Boolean).join('');return cards?`<section class="nearbyextras"><h3>축제 가는 김에</h3><div class="affiliategrid">${cards}</div></section>`:''}
function toPublicFestival(f){return {id:f.id,slug:f.slug||f.id,title:f.title,description:f.description,region:f.region,city:f.city,address:f.address,latitude:f.latitude,longitude:f.longitude,startDate:f.startDate,endDate:f.endDate,category:f.category,tags:[...(f.tags||[])],price:f.price,free:f.free,night:f.night,parking:f.parking??null,image:f.image,source:f.source??null,sourceUrl:f.sourceUrl??null,updatedAt:f.updatedAt??null,promoted:!!f.promoted,promotionPriority:f.promotionPriority||0,promotionStartDate:f.promotionStartDate||null,promotionEndDate:f.promotionEndDate||null}}
function imageFallback(img){img.parentElement.classList.add('fallback')}
function card(f,index=99){let shown=f.tags.slice(0,3).map(t=>`<span class="tag">${escapeHtml(tagLabels[t]||t)}</span>`).join(''),promotion=isPromotionActive(f)?'<span class="promotionlabel">프로모션</span>':'',price=f.free===true?'무료':f.free===false?(f.price||'유료'):'정보 없음',image=f.image?`<img src="${escapeHtml(f.image)}" alt="${escapeHtml(f.title)}" loading="${index<4?'eager':'lazy'}" decoding="async" ${index<2?'fetchpriority="high"':''} onerror="imageFallback(this)">`:'',selected=compareCandidates.includes(f.id);return `<article class="card" role="button" tabindex="0" aria-label="${escapeHtml(f.title)} 상세정보 보기" onclick="openDetail('${f.id}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();openDetail('${f.id}')} "><div class="photo ${f.image?'':'fallback'}">${image}<div class="imagefallback">✦ 전국축제달력<br><small>축제 이미지 준비중</small></div><span class="badge">${escapeHtml(getFestivalStatus(f))}</span>${promotion}${heartButton(f)}</div><div class="cardbody"><h3>${escapeHtml(f.title)}</h3><div class="info">⌖ ${escapeHtml(f.region)} ${escapeHtml(f.city)}<br>▣ ${fmt(f.startDate)} — ${fmt(f.endDate)}</div><span class="meta">${escapeHtml(f.category)} · ${escapeHtml(price)}</span><div class="tags">${shown}</div><button class="compareadd ${selected?'selected':''}" aria-pressed="${selected}" onclick="toggleCompare('${f.id}',event)">${selected?'✓ 비교 중':'+ 비교'}</button></div></article>`}
function distanceKm(a,b,c,d){let r=6371,p1=a*Math.PI/180,p2=c*Math.PI/180,dp=(c-a)*Math.PI/180,dl=(d-b)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*r*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function filtered(){let state=getFilterState();return sortFestivals(filterFestivals(festivals,state),state)}
let searchTimer;function debouncedRender(){clearTimeout(searchTimer);searchTimer=setTimeout(()=>{FestivalAnalytics.track('search',{query:query.value.trim()});renderCards()},200)}
function activeFilterList(){let items=[];if(query.value.trim())items.push(['query',`검색: ${query.value.trim()}`]);if(region.value!=='전체 지역')items.push(['region',regionName(region.value)]);if(category.value!=='전체 카테고리')items.push(['category',category.value]);if(price.value!=='전체 요금')items.push(['price',price.value]);if(period!=='all')items.push(['period',({today:'오늘',weekend:'이번 주말',nextWeekend:'다음 주말',ongoing:'진행중',endingSoon:'곧 끝나요'})[period]]);if(purpose!=='all')items.push(['purpose',tagLabels[purpose]]);if(quickFree)items.push(['quickFree','무료']);if(quickNight)items.push(['quickNight','야간']);if(nearMode)items.push(['near','내 주변']);return items}
function removeFilter(key){if(key==='query')query.value='';if(key==='region')region.value='전체 지역';if(key==='category')category.value='전체 카테고리';if(key==='price')price.value='전체 요금';if(key==='period'){period='all';document.querySelectorAll('[data-period]').forEach(b=>b.classList.toggle('active',b.dataset.period==='all'))}if(key==='purpose'){purpose='all';document.querySelectorAll('[data-purpose]').forEach(b=>b.classList.toggle('active',b.dataset.purpose==='all'))}if(key==='quickFree'){quickFree=false;freeChip.classList.remove('active')}if(key==='quickNight'){quickNight=false;nightChip.classList.remove('active')}if(key==='near'){nearMode=false;locationStatus.textContent=''}renderCards()}
function resetFilters(){query.value='';region.value='전체 지역';category.value='전체 카테고리';price.value='전체 요금';sort.value='recommended';period='all';purpose='all';quickFree=quickNight=nearMode=false;locationStatus.textContent='';document.querySelectorAll('[data-period]').forEach(b=>b.classList.toggle('active',b.dataset.period==='all'));document.querySelectorAll('[data-purpose]').forEach(b=>b.classList.toggle('active',b.dataset.purpose==='all'));freeChip.classList.remove('active');nightChip.classList.remove('active');renderCards()}
function saveCurrentFilters(){let saved=JSON.parse(localStorage.getItem('festival-saved-filters')||'[]'),state=getFilterState(),entry={region:state.region,category:state.category,price:state.price,period:state.period,purpose:state.purpose,freeOnly:state.freeOnly,nightOnly:state.nightOnly,savedAt:new Date().toISOString()};saved=[entry,...saved.filter(v=>JSON.stringify({...v,savedAt:undefined})!==JSON.stringify({...entry,savedAt:undefined}))].slice(0,5);localStorage.setItem('festival-saved-filters',JSON.stringify(saved));showToast('이 조건을 저장했습니다.')}
function renderActiveFilters(){let items=activeFilterList();activeFilters.classList.toggle('hidden',!items.length);activeFilters.innerHTML=items.length?`<b>선택한 조건</b>${items.map(([key,label])=>`<button class="activefilter" onclick="removeFilter('${key}')">${escapeHtml(label)} ×</button>`).join('')}<button class="savefilters" onclick="saveCurrentFilters()">이 조건 저장</button><button class="resetfilters" onclick="resetFilters()">전체 초기화</button>`:''}
function setMobileView(view,button){exploreView.classList.toggle('mobile-map',view==='map');document.querySelectorAll('[data-mobile-view]').forEach(b=>b.classList.toggle('active',b.dataset.mobileView===view));if(view==='map'&&map)setTimeout(()=>map.invalidateSize(),80)}
function toggleMobileFilters(){let open=filterPanel.classList.toggle('open');document.getElementById('mobileFilterButton')?.setAttribute('aria-expanded',String(open))}
function jumpToNearby(){showView('explore');setMobileView('map');document.querySelector('.mapsection')?.scrollIntoView({behavior:'smooth',block:'start'});findNearby()}
function focusRegionSearch(){showView('explore');filterPanel.classList.add('open');region.focus();region.scrollIntoView({behavior:'smooth',block:'center'})}
function setPeriod(value,button){period=value;document.querySelectorAll('[data-period]').forEach(b=>b.classList.toggle('active',b===button));renderCards()}
function setPurpose(value,button){purpose=value;document.querySelectorAll('[data-purpose]').forEach(b=>b.classList.toggle('active',b===button));renderCards()}
function toggleQuick(type,button){if(type==='free')quickFree=!quickFree;else quickNight=!quickNight;button.classList.toggle('active',type==='free'?quickFree:quickNight);renderCards()}
function renderCards(){filteredFestivals=filtered();let label=region.value==='전체 지역'?'전국':regionName(region.value),range=weekendRange(period==='nextWeekend'?1:0);resultCount.textContent=`조건에 맞는 축제 ${filteredFestivals.length}개`;listTitle.textContent=region.value==='전체 지역'?'전국 축제':`${label}에서 열리는 축제`;dateRangeLabel.textContent=period==='weekend'||period==='nextWeekend'?`${fmt(isoDate(range.start))} — ${fmt(isoDate(range.end))}`:`${fmt(isoDate(todayDate()))} 기준`;updatedLabel.textContent=datasetUpdatedAt?`축제 정보 업데이트: ${fmt(datasetUpdatedAt)}`:'';grid.innerHTML=filteredFestivals.length?renderFestivalFeed(filteredFestivals):'<div class="empty"><h3>조건에 맞는 축제가 없어요.</h3><p>조건을 줄이거나 이번 주말 전체 축제를 확인해보세요.</p><div class="emptyactions"><button onclick="resetFilters()">필터 초기화</button><button onclick="showThisWeekend()">이번 주말 전체 보기</button></div></div>';renderActiveFilters();renderMapMarkers(filteredFestivals);renderRecent();syncFilterUrl();FestivalAnalytics.track('filter_apply',{resultCount:filteredFestivals.length,period,region:region.value})}
function renderSkeletons(){grid.innerHTML=Array.from({length:4},()=>'<div class="card skeletoncard" aria-hidden="true"><div class="photo skeleton"></div><div class="cardbody"><div class="skeleton line wide"></div><div class="skeleton line"></div><div class="skeleton line short"></div></div></div>').join('');resultCount.textContent='축제 정보를 불러오는 중이에요.'}
function renderLoadError(){grid.innerHTML='<div class="empty"><h3>축제 정보를 불러오지 못했어요.</h3><p>네트워크 상태를 확인한 뒤 다시 시도해 주세요.</p><div class="emptyactions"><button onclick="initializeApp()">다시 시도</button></div></div>';resultCount.textContent='데이터 로딩 실패';festivalMap.innerHTML='<div class="empty">지도에 표시할 축제 정보를 불러오지 못했어요.</div>'}
function showThisWeekend(){resetFilters();let button=document.querySelector('[data-period="weekend"]');setPeriod('weekend',button)}
let toastTimer;function showToast(message){clearTimeout(toastTimer);toast.classList.remove('show');void toast.offsetWidth;toast.textContent=message;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),2000)}
function toggleFav(id,e){if(e){e.preventDefault();e.stopPropagation()}let adding=!favorites.includes(id);favorites=adding?[...favorites,id]:favorites.filter(v=>v!==id);FestivalStorage.write('festival-favorites',favorites);favCount.textContent=`찜 ${favorites.length}`;document.querySelectorAll(`[data-fav-id="${id}"]`).forEach(button=>{button.classList.toggle('liked',adding);button.classList.remove('pop');if(adding){void button.offsetWidth;button.classList.add('pop')}button.setAttribute('aria-pressed',adding);let f=festivals.find(v=>v.id===id);button.setAttribute('aria-label',`${f.title} 축제 ${adding?'찜 해제':'찜하기'}`);setTimeout(()=>button.classList.remove('pop'),400)});FestivalAnalytics.track('festival_favorite',{festivalId:id,action:adding?'add':'remove'});showToast(adding?'♥ 찜 목록에 추가되었습니다.':'찜 목록에서 삭제되었습니다.');if(!favoritesView.classList.contains('hidden'))setTimeout(updateFav,adding?0:330)}
function favoriteGroup(f){if(parseDate(f.endDate)<todayDate())return '지난 축제';if(isThisWeekend(f))return '이번 주말';if(isNextWeekend(f))return '다음 주말';if(active(f)&&getDaysUntilEnd(f)<=3)return '곧 종료';return '그 이후'}
function updateFav(){favCount.textContent=`찜 ${favorites.length}`;let list=festivals.filter(f=>favorites.includes(f.id));if(!list.length){favGrid.innerHTML='<div class="empty"><h3>아직 찜한 축제가 없어요.</h3><p>이번 주말에 갈 축제를 먼저 둘러보세요.</p><div class="emptyactions"><button onclick="showWeekendFromFavorites()">이번 주말 축제 둘러보기</button></div></div>';return}let urgent=list.filter(f=>active(f)&&getDaysUntilEnd(f)<=3),notice=urgent.length?`<div class="endingnotice">${urgent.map(f=>`${escapeHtml(f.title)}이(가) ${getDaysUntilEnd(f)===0?'오늘':`${getDaysUntilEnd(f)}일 후`} 종료돼요.`).join('<br>')}</div>`:'',order=['이번 주말','다음 주말','곧 종료','그 이후','지난 축제'];favGrid.innerHTML=notice+order.map(name=>{let items=list.filter(f=>favoriteGroup(f)===name);return items.length?`<section class="favgroup"><h3>${name} <span>${items.length}</span></h3><div class="grid">${items.map(card).join('')}</div></section>`:''}).join('')}
function showWeekendFromFavorites(){showView('explore');showThisWeekend();grid.scrollIntoView({behavior:'smooth',block:'start'})}
function summaryItems(f){let people=f.tags.filter(t=>['date','family','friends','solo'].includes(t)).map(t=>tagLabels[t]);return [`📍 ${f.region} ${f.city}`,`📅 ${fmt(f.startDate).slice(5)} — ${fmt(f.endDate).slice(5)}`,f.price?`💰 ${f.price}`:f.free===true?'💰 무료':null,f.night===true?'🌙 야간 운영':null,f.parking===true?'🚗 주차 가능':null,people.length?`👫 ${people.join(' · ')} 추천`:null,`⏰ ${getFestivalStatus(f)}`].filter(Boolean)}
function relatedFestivals(f){return festivals.filter(v=>v.id!==f.id&&parseDate(v.endDate)>=todayDate()).map(v=>({f:v,score:Number(v.region===f.region)*4+Number(v.category===f.category)*3+v.tags.filter(t=>f.tags.includes(t)).length+Number(Math.abs(parseDate(v.startDate)-parseDate(f.startDate))<=14*DAY)*2})).filter(v=>v.score>0).sort((a,b)=>b.score-a.score).slice(0,3).map(v=>v.f)}
function sourceBlock(f){if(!f.source&&!f.updatedAt&&!f.sourceUrl)return '';let link=f.sourceUrl&&getMonetizationUrl({url:f.sourceUrl})?`<a href="${escapeHtml(f.sourceUrl)}" target="_blank" rel="noopener noreferrer" onclick="FestivalAnalytics.track('official_site_click',{festivalId:'${escapeHtml(f.id)}'})">공식 정보 확인</a>`:'';return `<div class="sourcebox"><b>축제 정보 안내</b>${f.source?`<span>데이터 출처: ${escapeHtml(f.source)}</span>`:''}${f.updatedAt?`<span>최종 업데이트: ${fmt(f.updatedAt)}</span>`:''}${link}</div>`}
function rememberViewed(id){let ids=FestivalStorage.read('festival-recent',[]);ids=[id,...ids.filter(v=>v!==id)].slice(0,10);FestivalStorage.write('festival-recent',ids);renderRecent()}
function clearRecent(){FestivalStorage.write('festival-recent',[]);renderRecent();showToast('최근 본 기록을 지웠습니다.')}
function renderRecent(){let ids=FestivalStorage.read('festival-recent',[]),items=ids.map(id=>festivals.find(f=>f.id===id)).filter(Boolean).slice(0,6);recentSection.classList.toggle('hidden',!items.length);recentGrid.innerHTML=items.map(card).join('');document.getElementById('clearRecentButton')?.classList.toggle('hidden',!items.length)}
function festivalUrl(f){let url=new URL(location.href);url.searchParams.set('festival',f.slug||f.id);url.hash='';return url.href}
async function shareFestival(id){let f=festivals.find(v=>v.id===id),url=festivalUrl(f),data={title:`${f.title} 일정·위치·요금 | 전국축제달력`,text:f.description,url};try{if(navigator.share)await navigator.share(data);else if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(url);else throw new Error('Clipboard unavailable');FestivalAnalytics.track('festival_share',{festivalId:id,method:navigator.share?'web_share':'clipboard'});if(!navigator.share)showToast('축제 링크를 복사했습니다.')}catch(e){if(e.name!=='AbortError')showToast('링크를 복사하지 못했습니다. 주소창의 URL을 복사해 주세요.')}}
function updateDetailSeo(f){let title=`${f.title} 일정·위치·요금 | 전국축제달력`,url=festivalUrl(f);document.title=title;document.querySelector('meta[name="description"]').content=f.description;document.querySelector('meta[property="og:title"]').content=title;document.querySelector('meta[property="og:description"]').content=f.description;document.querySelector('meta[property="og:url"]').content=url;document.querySelector('meta[name="twitter:title"]').content=title;document.querySelector('meta[name="twitter:description"]').content=f.description;document.querySelector('link[rel="canonical"]').href=url;let schema={"@context":"https://schema.org","@type":"Event",name:f.title,startDate:f.startDate,endDate:f.endDate,description:f.description,image:f.image?[f.image]:undefined,eventAttendanceMode:'https://schema.org/OfflineEventAttendanceMode',location:{"@type":"Place",name:f.venue||f.address,address:f.address}};if(f.free)schema.offers={"@type":"Offer",price:'0',priceCurrency:'KRW',availability:'https://schema.org/InStock'};document.getElementById('festivalStructuredData')?.remove();let script=document.createElement('script');script.id='festivalStructuredData';script.type='application/ld+json';script.textContent=JSON.stringify(schema);document.head.appendChild(script)}
function initDetailMap(f){if(!window.L||!Number.isFinite(f.latitude)||!Number.isFinite(f.longitude))return;if(detailMap){detailMap.remove();detailMap=null}detailMap=L.map('detailMap',{zoomControl:true,scrollWheelZoom:false}).setView([f.latitude,f.longitude],14);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(detailMap);L.marker([f.latitude,f.longitude],{title:f.title}).addTo(detailMap);setTimeout(()=>detailMap?.invalidateSize(),80)}
function openDetail(id,updateUrl=true){let f=festivals.find(v=>v.id===id);if(!f)return;previousFocus=document.activeElement;currentFestivalId=id;rememberViewed(id);let summary=summaryItems(f).map(v=>`<div class="summaryitem">${escapeHtml(v)}</div>`).join(''),related=relatedFestivals(f),relatedHtml=related.length?`<section class="detailsection"><h3>이런 축제도 있어요</h3><div class="relatedgrid">${related.map(v=>`<button class="relatedcard" onclick="openDetail('${v.id}')"><b>${escapeHtml(v.title)}</b><br><small>${escapeHtml(v.region)} · ${escapeHtml(getFestivalStatus(v))}</small></button>`).join('')}</div></section>`:'',facts=[['기간',`${fmt(f.startDate)} — ${fmt(f.endDate)}`],['장소',f.venue||f.address],['요금',f.price||'정보 없음'],['문의',f.phone]].filter(([,value])=>value).map(([label,value])=>`<div class="fact"><b>${label}</b><br>${escapeHtml(value)}</div>`).join(''),report=appConfig.reportUrl?`<p class="disclosure"><a class="reportlink" href="${escapeHtml(appConfig.reportUrl)}" target="_blank" rel="noopener noreferrer">정보 오류 제보</a></p>`:'';detailHero.style.backgroundImage=f.image?`url('${f.image}')`:'none';detailContent.innerHTML=`<b class="orange">${escapeHtml(f.category)} · ${escapeHtml(f.region)}</b><h2 id="detailTitle">${escapeHtml(f.title)}</h2><section class="summary"><h3>5초 요약</h3><div class="summarygrid">${summary}</div></section><p>${escapeHtml(f.description)}</p><div class="facts">${facts}</div>${Number.isFinite(f.latitude)&&Number.isFinite(f.longitude)?'<section class="detailsection"><h3>축제 위치</h3><div id="detailMap" class="detailmap" aria-label="축제 위치 지도"></div></section>':''}${sourceBlock(f)}<div class="noticebox">축제 일정 및 운영정보는 변경될 수 있으니 방문 전 공식 정보를 확인해주세요.</div><div class="actions"><button class="primary" onclick="toggleFav('${f.id}');openDetail('${f.id}',false)">${favorites.includes(f.id)?'♥ 찜했어요':'♡ 찜하기'}</button><button class="primary" onclick="shareFestival('${f.id}')">↗ 공유하기</button></div>${relatedHtml}${renderFestivalExtras(f)}${report}`;modal.classList.remove('hidden');document.body.classList.add('modal-open');if(updateUrl){let url=festivalUrl(f);history.pushState({festival:f.id},'',url)}updateDetailSeo(f);FestivalAnalytics.track('festival_view',{festivalId:id});if(document.getElementById('detailMap'))initDetailMap(f);requestAnimationFrame(()=>modal.querySelector('.close')?.focus())}
function resetSeo(){document.title=SEO_DEFAULT.title;document.querySelector('meta[name="description"]').content=SEO_DEFAULT.description;document.querySelector('meta[property="og:title"]').content=SEO_DEFAULT.title;document.querySelector('meta[property="og:description"]').content='오늘과 이번 주말에 갈 축제를 빠르게 찾아보세요.';document.querySelector('meta[property="og:url"]').content=SEO_DEFAULT.url;document.querySelector('meta[name="twitter:title"]').content=SEO_DEFAULT.title;document.querySelector('link[rel="canonical"]').href=SEO_DEFAULT.url;document.getElementById('festivalStructuredData')?.remove()}
function closeDetail(options={}){if(!options.fromHistory&&history.state?.festival&&!history.state?.direct){history.back();return}modal.classList.add('hidden');document.body.classList.remove('modal-open');if(detailMap){detailMap.remove();detailMap=null}currentFestivalId=null;if(!options.fromHistory){let url=new URL(location.href);url.searchParams.delete('festival');history.replaceState(null,'',url.pathname+url.search+url.hash)}resetSeo();previousFocus?.focus?.();previousFocus=null}
function trapModalFocus(event){if(modal.classList.contains('hidden'))return;if(event.key==='Escape'){event.preventDefault();closeDetail();return}if(event.key!=='Tab')return;let focusable=[...modal.querySelectorAll('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')].filter(el=>!el.disabled),first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
function openAdInfo(){adModal.classList.remove('hidden');if(monetizationConfig.partnerContactUrl){let url=getMonetizationUrl({url:monetizationConfig.partnerContactUrl});if(url){adContactButton.disabled=false;adContactButton.className='primary';adContactButton.textContent='광고 문의';adContactButton.onclick=()=>window.open(url,'_blank','noopener,noreferrer')}}}
function closeAdInfo(){adModal.classList.add('hidden')}
function decisionContext(extra={}){return {weekend:true,region:region?.value||'전체 지역',position:userPosition,...extra}}
function decisionCard(item,source){let f=item.festival,reasons=item.reasons.length?item.reasons.slice(0,2):['일정과 정보를 기준으로 추천'];FestivalAnalytics.track('recommendation_reason_view',{festivalId:f.id,source});return `<article class="decisioncard" role="button" tabindex="0" onclick="FestivalAnalytics.track('${source==='top3'?'top3_click':'today_pick_click'}',{festivalId:'${f.id}'});openDetail('${f.id}')" onkeydown="if(event.key==='Enter'){openDetail('${f.id}')}">${f.image?`<img src="${escapeHtml(f.image)}" alt="${escapeHtml(f.title)}" loading="lazy">`:''}<div><span class="badge inlinebadge">${escapeHtml(getFestivalStatus(f))}</span><h3>${escapeHtml(f.title)}</h3><p>${escapeHtml(f.region)} ${escapeHtml(f.city)} · ${fmt(f.startDate)} — ${fmt(f.endDate)}</p><ul>${reasons.map(v=>`<li>${escapeHtml(v)}</li>`).join('')}</ul><button class="compareadd ${compareCandidates.includes(f.id)?'selected':''}" onclick="toggleCompare('${f.id}',event)">${compareCandidates.includes(f.id)?'✓ 비교 중':'+ 비교'}</button></div></article>`}
function renderTop3(){let w=weekendRange(0),items=festivals.filter(f=>overlaps(f,w.start,w.end)),ranked=FestivalDecision.selectDiverseRecommendations(items,decisionContext(),3);top3Section.classList.toggle('hidden',!ranked.length);top3Grid.innerHTML=ranked.map(v=>decisionCard(v,'top3')).join('');if(ranked.length)FestivalAnalytics.track('top3_view',{count:ranked.length})}
function showTodayPicks(){let items=festivals.filter(f=>active(f)),ranked=FestivalDecision.selectDiverseRecommendations(items,decisionContext({today:true,weekend:false}),3);todayPicksSection.classList.remove('hidden');todayPicksSection.innerHTML=`<div class="decisionhead"><div><b class="orange">TODAY PICKS</b><h2>오늘 갈까?</h2><p class="muted">오늘 축제 기간에 포함되는 곳 중 세 곳만 골랐어요.</p></div><button class="textbutton" onclick="todayPicksSection.classList.add('hidden')">닫기</button></div><div class="decisiongrid">${ranked.length?ranked.map(v=>decisionCard(v,'today')).join(''):'<div class="empty">오늘 진행 중인 축제가 없어요.</div>'}</div>`;FestivalAnalytics.track('today_pick_open',{count:ranked.length});todayPicksSection.scrollIntoView({behavior:'smooth',block:'start'})}
function toggleCompare(id,event){event?.stopPropagation();event?.preventDefault();let has=compareCandidates.includes(id);if(has){compareCandidates=compareCandidates.filter(v=>v!==id);FestivalAnalytics.track('compare_remove',{festivalId:id})}else{if(compareCandidates.length>=FestivalDecision.maxCompare){showToast('비교 후보는 최대 3개까지 담을 수 있어요.');return}compareCandidates=[...compareCandidates,id];FestivalAnalytics.track('compare_add',{festivalId:id})}FestivalDecision.setCompare(compareCandidates);renderCompareBar();renderCards();renderTop3();if(!compareView.classList.contains('hidden'))renderCompareView()}
function renderCompareBar(){let items=compareCandidates.map(id=>festivals.find(f=>f.id===id)).filter(Boolean);compareBar.classList.toggle('hidden',!items.length);compareBar.innerHTML=items.length?`<div><b>비교 후보 ${items.length}/3</b><span class="comparechips">${items.map(f=>`<span>${escapeHtml(f.title)} <button aria-label="${escapeHtml(f.title)} 비교에서 제거" onclick="toggleCompare('${f.id}',event)">×</button></span>`).join('')}</span></div><button class="primary" onclick="openCompare()">비교하기</button>`:''}
function compareValue(value){return value===null||value===undefined||value===''?'정보 없음':value}
function renderCompareView(){let items=compareCandidates.map(id=>festivals.find(f=>f.id===id)).filter(Boolean);compareGrid.innerHTML=items.length?items.map(f=>{let km=userPosition&&Number.isFinite(f.latitude)?`${distanceKm(userPosition.latitude,userPosition.longitude,f.latitude,f.longitude).toFixed(1)}km`:'정보 없음';return `<article class="compareitem">${f.image?`<img src="${escapeHtml(f.image)}" alt="${escapeHtml(f.title)}">`:''}<h3>${escapeHtml(f.title)}</h3><dl><div><dt>지역</dt><dd>${escapeHtml(compareValue(`${f.region} ${f.city}`))}</dd></div><div><dt>기간</dt><dd>${fmt(f.startDate)} — ${fmt(f.endDate)}</dd></div><div><dt>상태</dt><dd>${escapeHtml(getFestivalStatus(f))}</dd></div><div><dt>요금</dt><dd>${f.free===true?'무료':escapeHtml(compareValue(f.price))}</dd></div><div><dt>야간</dt><dd>${f.night===true?'운영':f.night===false?'미운영':'정보 없음'}</dd></div><div><dt>주차</dt><dd>${escapeHtml(compareValue(f.parking))}</dd></div><div><dt>추천</dt><dd>${escapeHtml((f.tags||[]).slice(0,3).map(t=>tagLabels[t]||t).join(' · ')||'정보 없음')}</dd></div><div><dt>분류</dt><dd>${escapeHtml(compareValue(f.category))}</dd></div><div><dt>거리</dt><dd>${km}</dd></div><div><dt>출처</dt><dd>${escapeHtml(compareValue(f.source))}</dd></div></dl><div class="compareactions"><button onclick="openDetail('${f.id}')">상세보기</button><button class="primary" onclick="chooseWeekendPlan('${f.id}')">이번 주말 계획에 담기</button><button onclick="toggleCompare('${f.id}',event)">제거</button></div></article>`}).join(''):'<div class="empty">카드에서 비교할 축제를 담아주세요.</div>'}
function openCompare(){FestivalAnalytics.track('compare_open',{count:compareCandidates.length});showView('compare');renderCompareView();scrollTo({top:0,behavior:'smooth'})}
function chooseWeekendPlan(id){FestivalDecision.setWeekendPlan(id);FestivalAnalytics.track('weekend_plan_add',{festivalId:id});showToast('이번 주말 계획에 담았습니다.');renderWeekendPlan();showView('explore')}
function removeWeekendPlan(){let plan=FestivalDecision.getWeekendPlan();FestivalDecision.clearWeekendPlan();FestivalAnalytics.track('weekend_plan_remove',{festivalId:plan?.festivalId});showToast('이번 주말 계획에서 삭제했습니다.');renderWeekendPlan()}
function renderWeekendPlan(){let plan=FestivalDecision.getWeekendPlan(),f=plan&&festivals.find(v=>v.id===plan.festivalId);weekendPlanSection.classList.toggle('hidden',!f);weekendPlanSection.innerHTML=f?`<div class="plancontent"><div><b class="orange">MY WEEKEND PLAN</b><h2>${escapeHtml(f.title)}</h2><p>${escapeHtml(f.region)} ${escapeHtml(f.city)} · ${fmt(f.startDate)} — ${fmt(f.endDate)}</p></div><div class="planactions"><button onclick="openDetail('${f.id}')">상세보기</button><button onclick="openCompare()">변경하기</button><button onclick="removeWeekendPlan()">삭제</button></div></div>`:''}
function renderDecisionFeatures(){renderTop3();renderWeekendPlan();renderCompareBar()}
function openRecommendation(){recommend.classList.remove('hidden');recommend.innerHTML=`<div class="recform"><select id="recWho" aria-label="누구와 가나요"><option value="all">누구와: 상관없음</option><option value="date">연인</option><option value="family">가족</option><option value="friends">친구</option><option value="solo">혼자</option></select><select id="recType" aria-label="어떤 축제를 원하나요"><option value="all">종류: 상관없음</option><option value="food">먹거리</option><option value="night">야간</option><option value="performance">공연</option><option value="traditional">전통</option><option value="nature">자연</option><option value="experience">체험</option></select><select id="recCost" aria-label="비용"><option value="all">비용: 상관없음</option><option value="free">무료</option></select></div><button class="primary" onclick="recommendFestivals()">맞춤 추천 3곳 보기</button><div id="recResults"></div>`;FestivalAnalytics.track('recommendation_view')}
function recommendationScore(f,choices){let score=0,reasons=[],w=weekendRange(0);if(overlaps(f,w.start,w.end)){score+=3;reasons.push('이번 주말 진행')}if(choices.who!=='all'&&f.tags.includes(choices.who)){score+=3;reasons.push(`${tagLabels[choices.who]} 추천`)}if(choices.type!=='all'&&(f.tags.includes(choices.type)||f.category.toLowerCase().includes(choices.type))){score+=2;reasons.push(`${tagLabels[choices.type]||choices.type} 축제`)}if(choices.cost==='free'&&f.free===true){score+=1;reasons.push('무료')}if(active(f)&&getDaysUntilEnd(f)<=3){score+=1;reasons.push('종료 임박')}if(region.value!=='전체 지역'&&f.region===region.value){score+=2;reasons.push(`${regionName(f.region)} 지역`)}return {festival:f,score,reasons}}
function recommendFestivals(){let choices={who:recWho.value,type:recType.value,cost:recCost.value},w=weekendRange(0),candidates=festivals.filter(f=>overlaps(f,w.start,w.end)&&(choices.cost!=='free'||f.free===true)),list=FestivalDecision.selectDiverseRecommendations(candidates,decisionContext({who:choices.who,type:choices.type,freeOnly:choices.cost==='free'}),3);recResults.innerHTML=`<b style="display:block;margin-top:12px">이번 주말에는 여기 어때요?</b>`+(list.length?`<div class="recresults">${list.map(({festival:f,reasons})=>`<button class="reccard" onclick="FestivalAnalytics.track('recommendation_click',{festivalId:'${f.id}'});openDetail('${f.id}')"><b>${escapeHtml(f.title)}</b><small>${escapeHtml(f.region)} · ${escapeHtml(getFestivalStatus(f))} · ${f.free===true?'무료':'유료'}</small><em>왜 추천했나요? ${escapeHtml(reasons.slice(0,2).join(' · '))}</em></button>`).join('')}</div>`:'<p>조건에 맞는 축제가 없어요. 조건을 조금 넓혀보세요.</p>')}
function showView(v){['explore','calendar','compare','favorites'].forEach(x=>document.getElementById(x+'View').classList.toggle('hidden',x!==v));hero.classList.toggle('hidden',v!=='explore');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='calendar')renderCalendar();if(v==='favorites')updateFav()}
function moveMonth(n){month=new Date(month.getFullYear(),month.getMonth()+n,1);renderCalendar()}
function renderCalendar(){calTitle.textContent=`${month.getFullYear()}년 ${month.getMonth()+1}월`;let start=new Date(month.getFullYear(),month.getMonth(),1),first=new Date(start);first.setDate(1-start.getDay());let html='',todayIso=isoDate(todayDate());for(let i=0;i<42;i++){let d=new Date(first);d.setDate(first.getDate()+i);let iso=isoDate(d),count=festivals.filter(f=>f.startDate<=iso&&f.endDate>=iso).length,density=count>=6?'high':count>=3?'medium':count?'low':'';html+=`<button class="day ${d.getMonth()!==month.getMonth()?'off':''} ${iso===todayIso?'today':''} ${density}" aria-label="${fmt(iso)} ${count?`축제 ${count}개`:'축제 없음'}" onclick="selectDay('${iso}')"><b>${d.getDate()}</b>${count?`<span class="dot">축제 ${count}개</span>`:''}</button>`}days.innerHTML=html}
function selectDay(iso){let list=festivals.filter(f=>f.startDate<=iso&&f.endDate>=iso);selectedTitle.textContent=`${fmt(iso)} 진행 축제 ${list.length}`;dayGrid.innerHTML=list.length?list.map(card).join(''):'<div class="empty">이날 진행하는 축제가 없어요.</div>';selectedTitle.scrollIntoView({behavior:'smooth',block:'start'})}
const regionLabels={서울:'서울',경기:'경기도',강원:'강원도',부산:'부산',전북:'전북',인천:'인천',충남:'충남',제주:'제주'};function regionName(v){return regionLabels[v]||v}
function markerPopup(f){let id=escapeHtml(f.id),title=escapeHtml(f.title),place=escapeHtml(`${f.region} ${f.city}`),period=escapeHtml(`${fmt(f.startDate)} — ${fmt(f.endDate)} · ${f.free?'무료':'유료'}`);return `<article class="popupcard" onclick="openDetail('${id}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();openDetail('${id}')}" role="button" tabindex="0"><img src="${escapeHtml(f.image)}" alt=""><div class="popupbody"><span class="popupstatus">${escapeHtml(getFestivalStatus(f))}</span><h3>${title}</h3><div class="popupmeta">${place}<br>${period}</div></div></article>`}
function initMap(){map=L.map('festivalMap',{minZoom:6,maxZoom:18,zoomControl:true}).setView([36.35,127.85],7);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);markerLayer=L.markerClusterGroup({chunkedLoading:true,removeOutsideVisibleBounds:true,showCoverageOnHover:false,zoomToBoundsOnClick:true,iconCreateFunction:c=>L.divIcon({html:`<div class="cluster-marker">${c.getChildCount()}</div>`,className:'',iconSize:[42,42]})});map.addLayer(markerLayer);mapRegions.innerHTML=['전체 지역',...new Set(festivals.map(f=>f.region))].map(v=>`<button class="mapregion ${v==='전체 지역'?'active':''}" data-map-region="${v}" onclick="selectRegion('${v}')">${v==='전체 지역'?'전국':regionName(v)}</button>`).join('');renderCards();setTimeout(()=>map.invalidateSize(),50)}
function openMapSheet(f){let sheet=document.getElementById('mapSheet');if(!sheet)return;sheet.innerHTML=`<button class="sheetclose" aria-label="지도 미리보기 닫기" onclick="closeMapSheet()">×</button><div class="sheetbody" role="button" tabindex="0" onclick="openDetail('${f.id}')" onkeydown="if(event.key==='Enter'){openDetail('${f.id}')} ">${f.image?`<img src="${escapeHtml(f.image)}" alt="" decoding="async">`:''}<div><span class="popupstatus">${escapeHtml(getFestivalStatus(f))}</span><h3>${escapeHtml(f.title)}</h3><p>${escapeHtml(f.region)} ${escapeHtml(f.city)} · ${fmt(f.startDate)} — ${fmt(f.endDate)}</p></div></div>${heartButton(f)}`;sheet.classList.add('show')}
function openMapSheetById(id){if(matchMedia('(max-width:560px)').matches){let festival=festivals.find(f=>f.id===id);if(festival)openMapSheet(festival)}}
function closeMapSheet(){document.getElementById('mapSheet')?.classList.remove('show')}
function renderMapMarkers(list){if(!markerLayer)return;markerLayer.clearLayers();let mappable=list.filter(f=>Number.isFinite(f.latitude)&&Number.isFinite(f.longitude));mappable.forEach(f=>{let icon=L.divIcon({html:`<div class="festival-marker" onclick="openMapSheetById('${escapeHtml(f.id)}')"></div>`,className:'',iconSize:[20,20],iconAnchor:[10,20],popupAnchor:[0,-18]}),m=L.marker([f.latitude,f.longitude],{icon,title:f.title,alt:f.title});m.bindTooltip(f.title,{direction:'top',offset:[0,-18]});m.bindPopup(markerPopup(f),{className:'map-popup',maxWidth:240,autoPanPadding:[28,28]});m.on('click',()=>FestivalAnalytics.track('map_marker_click',{festivalId:f.id}));m.on('popupopen',()=>{if(matchMedia('(max-width:560px)').matches){m.closePopup();openMapSheet(f)}});markerLayer.addLayer(m)});mapCount.textContent=`${region.value==='전체 지역'?'전국':regionName(region.value)} 축제 ${list.length}개`;document.querySelectorAll('[data-map-region]').forEach(b=>b.classList.toggle('active',b.dataset.mapRegion===region.value))}
function selectRegion(value){region.value=value;nearMode=false;renderCards();let list=filtered().filter(f=>Number.isFinite(f.latitude)&&Number.isFinite(f.longitude));if(!map)return;if(value==='전체 지역')map.setView([36.35,127.85],7);else if(list.length){let bounds=L.latLngBounds(list.map(f=>[f.latitude,f.longitude]));map.fitBounds(bounds.pad(.5),{maxZoom:10})}document.getElementById('grid').scrollIntoView({behavior:'smooth',block:'start'})}
function findNearby(){if(!navigator.geolocation){locationStatus.textContent='이 브라우저에서는 위치 기능을 지원하지 않아요.';return}locationStatus.textContent='현재 위치를 확인하고 있어요…';navigator.geolocation.getCurrentPosition(pos=>{userPosition=pos.coords;nearMode=true;locationStatus.textContent=`현재 위치 기준 ${distance.value}km 이내 축제를 표시합니다.`;if(!sort.querySelector('[value="distance"]'))sort.add(new Option('거리순','distance'));if(userMarker)map.removeLayer(userMarker);userMarker=L.circleMarker([pos.coords.latitude,pos.coords.longitude],{radius:7,color:'#0f172a',weight:3,fillColor:'#fff',fillOpacity:1}).addTo(map).bindTooltip('내 위치');renderCards();map.setView([pos.coords.latitude,pos.coords.longitude],10) },()=>{nearMode=false;locationStatus.textContent='위치 권한 없이도 다른 기능을 계속 이용할 수 있어요.'},{enableHighAccuracy:false,timeout:8000,maximumAge:300000})}
function applyDistance(){if(userPosition){nearMode=true;locationStatus.textContent=`현재 위치 기준 ${distance.value}km 이내 축제를 표시합니다.`;renderCards()}}
window.Monetization={config:monetizationConfig,items:monetizationItems,schemas:{item:monetizationItemSchema,festivalFields:festivalSchemaFields,radarPlus:radarPlusPreferenceSchema},getMonetizationUrl,trackMonetizationClick,renderSponsoredCard,renderFestivalExtras,toPublicFestival};
function populateControls(){region.innerHTML='<option>전체 지역</option>';category.innerHTML='<option>전체 카테고리</option>';[...new Set(festivals.map(f=>f.region).filter(Boolean))].forEach(v=>region.add(new Option(v,v)));[...new Set(festivals.map(f=>f.category).filter(Boolean))].forEach(v=>category.add(new Option(v,v)));festivalSuggestions.innerHTML=[...new Set(festivals.flatMap(f=>[f.title,f.region,f.city,`${regionName(f.region)} ${f.city}`]).filter(Boolean))].map(v=>`<option value="${escapeHtml(v)}"></option>`).join('')}
async function initializeApp(){renderSkeletons();try{let data=await FestivalData.loadFestivals();festivals=data.items;datasetUpdatedAt=data.updatedAt;populateControls();applyUrlFilterState();updateFav();renderRecent();renderDecisionFeatures();if(window.L&&L.markerClusterGroup){if(map){markerLayer.clearLayers();renderCards()}else initMap()}else{festivalMap.innerHTML='<div class="empty">지도를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.</div>';renderCards()}let requested=new URLSearchParams(location.search).get('festival'),requestedFestival=festivals.find(f=>f.slug===requested||f.id===requested);history.replaceState(requestedFestival?{festival:requestedFestival.id,direct:true}:null,'',location.href);if(requestedFestival)setTimeout(()=>openDetail(requestedFestival.id,false),100)}catch(error){console.error('[festival-data] 데이터를 불러오지 못했습니다.',error);renderLoadError()}}
initTheme();document.addEventListener('keydown',trapModalFocus);window.addEventListener('popstate',()=>{applyUrlFilterState();let value=new URLSearchParams(location.search).get('festival'),f=festivals.find(v=>v.slug===value||v.id===value);if(f)openDetail(f.id,false);else if(!modal.classList.contains('hidden'))closeDetail({fromHistory:true});else renderCards()});initializeApp();
