(function(){
  const COMPARE_KEY='festival-compare',PLAN_KEY='festival-weekend-plan',MAX_COMPARE=3;
  const weights={weekend:40,today:45,active:18,free:8,night:7,preference:22,region:12,distance:14,endingSoon:6};
  const read=(key,fallback)=>window.FestivalStorage?.read(key,fallback)??fallback;
  const write=(key,value)=>window.FestivalStorage?.write(key,value);
  function reasons(f,context={}){let r=[];if(context.today&&active(f))r.push('오늘 축제 기간에 포함됩니다');if(context.weekend&&isThisWeekend(f))r.push('이번 주말에 열려요');if(context.who&&context.who!=='all'&&f.tags.includes(context.who))r.push(`${tagLabels[context.who]} 추천`);if(context.type&&context.type!=='all'&&(f.tags.includes(context.type)||f.category.toLowerCase().includes(context.type)))r.push(`${tagLabels[context.type]||context.type} 취향`);if(context.freeOnly&&f.free===true)r.push('무료로 즐겨요');if(f.night)r.push('야간에도 즐겨요');if(active(f)&&getDaysUntilEnd(f)<=3)r.push('종료 전에 서둘러야 해요');if(context.region&&context.region!=='전체 지역'&&f.region===context.region)r.push(`${regionName(f.region)}에서 가까워요`);if(context.position&&Number.isFinite(f.latitude)){let km=distanceKm(context.position.latitude,context.position.longitude,f.latitude,f.longitude);if(km<=50)r.push(`현재 위치에서 약 ${Math.round(km)}km`)}return [...new Set(r)]}
  function score(f,context={}){let s=0;if(context.today&&active(f))s+=weights.today;if(context.weekend&&isThisWeekend(f))s+=weights.weekend;if(active(f))s+=weights.active;if(f.free)s+=weights.free;if(f.night)s+=weights.night;if(context.who&&context.who!=='all'&&f.tags.includes(context.who))s+=weights.preference;if(context.type&&context.type!=='all'&&(f.tags.includes(context.type)||f.category.toLowerCase().includes(context.type)))s+=weights.preference;if(context.freeOnly&&f.free)s+=weights.preference;if(context.region&&context.region!=='전체 지역'&&f.region===context.region)s+=weights.region;if(active(f)&&getDaysUntilEnd(f)<=3)s+=weights.endingSoon;if(context.position&&Number.isFinite(f.latitude)){let km=distanceKm(context.position.latitude,context.position.longitude,f.latitude,f.longitude);s+=Math.max(0,weights.distance-Math.floor(km/10))}return {festival:f,score:s,reasons:reasons(f,context)}}
  function select(list,context={},limit=3){let ranked=list.map(f=>score(f,context)).sort((a,b)=>b.score-a.score||parseDate(a.festival.endDate)-parseDate(b.festival.endDate)),picked=[];for(let item of ranked){let sameRegion=picked.filter(x=>x.festival.region===item.festival.region).length,sameCategory=picked.filter(x=>x.festival.category===item.festival.category).length;if(sameRegion<2&&sameCategory<2)picked.push(item);if(picked.length===limit)break}for(let item of ranked){if(picked.length===limit)break;if(!picked.some(x=>x.festival.id===item.festival.id))picked.push(item)}return picked}
  function compareIds(){return read(COMPARE_KEY,[]).filter(v=>typeof v==='string').slice(0,MAX_COMPARE)}
  function setCompare(ids){write(COMPARE_KEY,[...new Set(ids)].slice(0,MAX_COMPARE))}
  function weekendKey(){return isoDate(weekendRange(0).start)}
  function plan(){let value=read(PLAN_KEY,null);return value&&value.targetWeekend===weekendKey()?value:null}
  function setPlan(festivalId){let value={festivalId,selectedAt:new Date().toISOString(),targetWeekend:weekendKey()};write(PLAN_KEY,value);return value}
  function clearPlan(){write(PLAN_KEY,null)}
  window.FestivalDecision={weights,scoreFestival:score,getRecommendationReasons:reasons,selectDiverseRecommendations:select,compareIds,setCompare,maxCompare:MAX_COMPARE,getWeekendPlan:plan,setWeekendPlan:setPlan,clearWeekendPlan:clearPlan,getTargetWeekend:weekendKey};
})();
